[package]
name = "level"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
common = { path = "../common" }
nbt = { path = "../nbt" }
tokio = { version = "1.26.0", features = ["rt", "time"] }
tokio-util = "0.7.7"
tracing = "0.1.37"

[build-dependencies]
cmake = "0.1.49"
