edition = "2021"
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 80
merge_derives = true
newline_style = "Native"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
struct_lit_width = 40
struct_variant_width = 40
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true